organization:
  name: 
  id: 
  address:
    street: 
    area: 
    country: Norge
  contact:
    email: 
    phone: 

invoices:
  - customer:
      name: 
      co: 
      address:
        street: 
        area: 
        country: Norge
    id: 
    date: 
    expiry_offset: 10
    payment_account: 
    hours:
      - date: 
        description: 
        duration: 
        per: 
    drives:
      - date: 
        start: 
        end: 
        distance: 
        per: 
    expenses:
      - date: 
        description: 
        quantity: 
        per: 